<?xml version='1.0' encoding='UTF-8' standalone='yes'?>

<!DOCTYPE Workspace
[
    <!ELEMENT Workspace (Function*,Value*,Ravel*,SymbolTable,
                         Symbol*,Commands?,StateIndicator)>
    <!ATTLIST Workspace  wsid       CDATA #REQUIRED>
    <!ATTLIST Workspace  year       CDATA #REQUIRED>
    <!ATTLIST Workspace  month      CDATA #REQUIRED>
    <!ATTLIST Workspace  day        CDATA #REQUIRED>
    <!ATTLIST Workspace  hour       CDATA #REQUIRED>
    <!ATTLIST Workspace  minute     CDATA #REQUIRED>
    <!ATTLIST Workspace  second     CDATA #REQUIRED>
    <!ATTLIST Workspace  timezone   CDATA #REQUIRED>
    <!ATTLIST Workspace  saving_SVN CDATA #REQUIRED>

        <!ELEMENT Value (#PCDATA)>
        <!ATTLIST Value flg    CDATA #REQUIRED>
        <!ATTLIST Value vid    CDATA #REQUIRED>
        <!ATTLIST Value parent CDATA #IMPLIED>
        <!ATTLIST Value rk     CDATA #REQUIRED>
        <!ATTLIST Value sh-0   CDATA #IMPLIED>
        <!ATTLIST Value sh-1   CDATA #IMPLIED>
        <!ATTLIST Value sh-2   CDATA #IMPLIED>
        <!ATTLIST Value sh-3   CDATA #IMPLIED>
        <!ATTLIST Value sh-4   CDATA #IMPLIED>
        <!ATTLIST Value sh-5   CDATA #IMPLIED>
        <!ATTLIST Value sh-6   CDATA #IMPLIED>
        <!ATTLIST Value sh-7   CDATA #IMPLIED>

        <!ELEMENT Ravel (#PCDATA)>
        <!ATTLIST Ravel vid    CDATA #REQUIRED>
        <!ATTLIST Ravel cells  CDATA #REQUIRED>

        <!ELEMENT SymbolTable (Symbol*)>
        <!ATTLIST SymbolTable size CDATA #REQUIRED>

            <!ELEMENT Symbol (unused-name|Variable|Function|
                              Label|Shared-Variable)*>
            <!ATTLIST Symbol name       CDATA #REQUIRED>
            <!ATTLIST Symbol stack-size CDATA #REQUIRED>

                <!ELEMENT unused-name EMPTY>

                <!ELEMENT Variable (#PCDATA)>
                <!ATTLIST Variable vid CDATA #REQUIRED>

                <!ELEMENT Function (UCS*)>
                <!ATTLIST Function fid             CDATA #REQUIRED>
                <!ATTLIST Function creation-time   CDATA #IMPLIED>
                <!ATTLIST Function LO-fid          CDATA #IMPLIED>
                <!ATTLIST Function OPER-fid        CDATA #IMPLIED>
                <!ATTLIST Function RO-fid          CDATA #IMPLIED>
                <!ATTLIST Function AXIS-vid        CDATA #IMPLIED>
                <!ATTLIST Function exec-properties CDATA #IMPLIED>
                <!ATTLIST Function macro           CDATA #IMPLIED>
                <!ATTLIST Function tag             CDATA #IMPLIED>

                <!ELEMENT Label (#PCDATA)>
                <!ATTLIST Label value CDATA #REQUIRED>

                <!ELEMENT Shared-Variable (#PCDATA)>
                <!ATTLIST Shared-Variable key CDATA #REQUIRED>

        <!ELEMENT UCS (#PCDATA)>
        <!ATTLIST UCS uni CDATA #REQUIRED>

        <!ELEMENT Commands (Command*)>
        <!ATTLIST Commands size CDATA #REQUIRED>

            <!ELEMENT Command (#PCDATA)>
            <!ATTLIST Command name       CDATA #REQUIRED>
            <!ATTLIST Command mode       CDATA #REQUIRED>
            <!ATTLIST Command fun       CDATA #REQUIRED>

        <!ELEMENT StateIndicator (SI-entry*)>
        <!ATTLIST StateIndicator levels CDATA #REQUIRED>

            <!ELEMENT SI-entry ((Execute|Statements|UserFunction),Parser+)>
            <!ATTLIST SI-entry level     CDATA #REQUIRED>
            <!ATTLIST SI-entry pc        CDATA #REQUIRED>
            <!ATTLIST SI-entry line      CDATA #REQUIRED>

                <!ELEMENT Statements (UCS)>

                <!ELEMENT Execute (UCS)>

                <!ELEMENT UserFunction (#PCDATA)>
                <!ATTLIST UserFunction ufun-name       CDATA #IMPLIED>
                <!ATTLIST UserFunction macro-num       CDATA #IMPLIED>
                <!ATTLIST UserFunction lambda-name     CDATA #IMPLIED>
                <!ATTLIST UserFunction symbol-level    CDATA #IMPLIED>

                <!ELEMENT Parser (Token*,Function*)>
                <!ATTLIST Parser size           CDATA #REQUIRED>
                <!ATTLIST Parser assign-pending CDATA #REQUIRED>
                <!ATTLIST Parser lookahead-high CDATA #REQUIRED>
                <!ATTLIST Parser action         CDATA #REQUIRED>
                    <!ELEMENT Token (#PCDATA)>
                    <!ATTLIST Token pc           CDATA #REQUIRED>
                    <!ATTLIST Token tag          CDATA #REQUIRED>
                    <!ATTLIST Token char         CDATA #IMPLIED>
                    <!ATTLIST Token int          CDATA #IMPLIED>
                    <!ATTLIST Token float        CDATA #IMPLIED>
                    <!ATTLIST Token real         CDATA #IMPLIED>
                    <!ATTLIST Token imag         CDATA #IMPLIED>
                    <!ATTLIST Token sym          CDATA #IMPLIED>
                    <!ATTLIST Token line         CDATA #IMPLIED>
                    <!ATTLIST Token vid          CDATA #IMPLIED>
                    <!ATTLIST Token index        CDATA #IMPLIED>
                    <!ATTLIST Token fun-id       CDATA #IMPLIED>
                    <!ATTLIST Token ufun-name    CDATA #IMPLIED>
                    <!ATTLIST Token symbol-level CDATA #IMPLIED>
                    <!ATTLIST Token comment      CDATA #IMPLIED>

]>

    <!-- hour/minute/second is )SAVE time in UTC (aka. GMT).
         timezone is offset to UTC in seconds.
         local time is UTC + offset -->

<Workspace wsid="save_load_SI" year="2021" month="1" day="19"
           hour="21" minute="13" second="51" timezone="-3600"
           saving_SVN=" 1406">

  <!-- system functions and primitives... -->
  <Function fid="0x9029C0" tag="0x41010907"/>   <!-- primitive: ⎕AF -->
  <Function fid="0x902980" tag="0x41090907"/>   <!-- primitive: ⎕AT -->
  <Function fid="0xCD8160" tag="0x43080907"/>   <!-- primitive: ⎕CR -->
  <Function fid="0x902940" tag="0x44040907"/>   <!-- primitive: ⎕DL -->
  <Function fid="0x902A60" tag="0x44070907"/>   <!-- primitive: ⎕DLX -->
  <Function fid="0x902900" tag="0x45010907"/>   <!-- primitive: ⎕EA -->
  <Function fid="0x9028C0" tag="0x45130907"/>   <!-- primitive: ⎕EB -->
  <Function fid="0xCD8100" tag="0x45030907"/>   <!-- primitive: ⎕EC -->
  <Function fid="0x902880" tag="0x45090907"/>   <!-- primitive: ⎕ENV -->
  <Function fid="0xCD80A0" tag="0x450D0907"/>   <!-- primitive: ⎕ES -->
  <Function fid="0x902840" tag="0x45100907"/>   <!-- primitive: ⎕EX -->
  <Function fid="0x902AE0" tag="0x46070907"/>   <!-- primitive: ⎕FFT -->
  <Function fid="0x902B40" tag="0x46060907"/>   <!-- primitive: ⎕FIO -->
  <Function fid="0x902BC0" tag="0x46050907"/>   <!-- primitive: ⎕FX -->
  <Function fid="0x902C60" tag="0x47020907"/>   <!-- primitive: ⎕GTK -->
  <Function fid="0x902CC0" tag="0x4D040907"/>   <!-- primitive: ⎕MAP -->
  <Function fid="0x902800" tag="0x49060907"/>   <!-- primitive: ⎕INP -->
  <Function fid="0x9027C0" tag="0x4E010907"/>   <!-- primitive: ⎕NA -->
  <Function fid="0x902780" tag="0x4E030907"/>   <!-- primitive: ⎕NC -->
  <Function fid="0x902740" tag="0x4E040907"/>   <!-- primitive: ⎕NL -->
  <Function fid="0x902DA0" tag="0x500B0907"/>   <!-- primitive: ⎕PLOT -->
  <Function fid="0x902E00" tag="0x53130907"/>   <!-- primitive: ⎕RE -->
  <Function fid="0x902E60" tag="0x52160907"/>   <!-- primitive: ⎕RVAL -->
  <Function fid="0x902700" tag="0x53040907"/>   <!-- primitive: ⎕SI -->
  <Function fid="0x9030A0" tag="0x53160907"/>   <!-- primitive: ⎕SQL -->
  <Function fid="0x903240" tag="0x530B0907"/>   <!-- primitive: ⎕SVC -->
  <Function fid="0x903200" tag="0x530D0907"/>   <!-- primitive: ⎕SVO -->
  <Function fid="0x9031C0" tag="0x530E0907"/>   <!-- primitive: ⎕SVQ -->
  <Function fid="0x903180" tag="0x530F0907"/>   <!-- primitive: ⎕SVR -->
  <Function fid="0x903140" tag="0x53100907"/>   <!-- primitive: ⎕SVS -->
  <Function fid="0x902680" tag="0x53150907"/>   <!-- primitive: ⎕STOP -->
  <Function fid="0x9032A0" tag="0x54030907"/>   <!-- primitive: ⎕TF -->
  <Function fid="0x903300" tag="0x58020907"/>   <!-- primitive: ⎕XML -->
  <Function fid="0x902640" tag="0x54080907"/>   <!-- primitive: ⎕TRACE -->
  <Function fid="0x9026C0" tag="0x55010907"/>   <!-- primitive: ⎕UCS -->
  <Function fid="0x8F5220" tag="0x43040907"/>   <!-- primitive: , -->
  <Function fid="0x8F51E0" tag="0x43050907"/>   <!-- primitive: ⍪ -->
  <Function fid="0x8F5280" tag="0x44050907"/>   <!-- primitive: ⌹ -->
  <Function fid="0x8F53A0" tag="0x46040907"/>   <!-- primitive: ⍕ -->
  <Function fid="0x8F52E0" tag="0x49020907"/>   <!-- primitive: ⍳ -->
  <Function fid="0x8F5440" tag="0x50010907"/>   <!-- primitive: ⊂ -->
  <Function fid="0x8F5400" tag="0x50020907"/>   <!-- primitive: ⊃ -->
  <Function fid="0x8F54E0" tag="0x53070907"/>   <!-- primitive: ⍋ -->
  <Function fid="0x8F54A0" tag="0x53080907"/>   <!-- primitive: ⍒ -->
  <Function fid="0x8F5580" tag="0x54010907"/>   <!-- primitive: ↑ -->
  <Function fid="0x8F5540" tag="0x44060907"/>   <!-- primitive: ↓ -->
  <Function fid="0x8F55E0" tag="0x43060909"/>   <!-- primitive: ⍨ -->
  <Function fid="0x8F5640" tag="0x45020909"/>   <!-- primitive: ¨ -->
  <Function fid="0x8F5980" tag="0x52080909"/>   <!-- primitive: / -->
  <Function fid="0x8F5940" tag="0x52090909"/>   <!-- primitive: ⌿ -->
  <Function fid="0x8F5A20" tag="0x53010909"/>   <!-- primitive: \ -->
  <Function fid="0x8F59E0" tag="0x53020909"/>   <!-- primitive: ⍀ -->
  <Function fid="0x8F5780" tag="0x4908090A"/>   <!-- primitive: . -->
  <Function fid="0x8F5880" tag="0x4A010907"/>   <!-- primitive: ∘ -->
  <Function fid="0x8F5840" tag="0x4F05090A"/>   <!-- primitive: ∘. -->
  <Function fid="0x8F56A0" tag="0x500A090A"/>   <!-- primitive: ⍣ -->
  <Function fid="0x8F58E0" tag="0x5206090A"/>   <!-- primitive: ⍤ -->
  <Function fid="0x9024E0" tag="0x5A010906"/>   <!-- primitive: ⍬ -->
  <Function fid="0x9024A0" tag="0x45110907"/>   <!-- primitive: ⍎ -->
  <Function fid="0x902460" tag="0x49010907"/>   <!-- primitive: ⌷ -->
  <Function fid="0x902420" tag="0x45040907"/>   <!-- primitive: ∈ -->
  <Function fid="0x9023E0" tag="0x450B0907"/>   <!-- primitive: ≡ -->
  <Function fid="0x9023A0" tag="0x4E080907"/>   <!-- primitive: ≢ -->
  <Function fid="0x902360" tag="0x45060907"/>   <!-- primitive: ⊤ -->
  <Function fid="0x902320" tag="0x44010907"/>   <!-- primitive: ⊥ -->
  <Function fid="0x9022E0" tag="0x52140907"/>   <!-- primitive: ⌽ -->
  <Function fid="0x9022A0" tag="0x52150907"/>   <!-- primitive: ⊖ -->
  <Function fid="0x902260" tag="0x54050907"/>   <!-- primitive: ⍉ -->
  <Function fid="0x902220" tag="0x520E0907"/>   <!-- primitive: ⍴ -->
  <Function fid="0x9021A0" tag="0x55040907"/>   <!-- primitive: ∪ -->
  <Function fid="0x9021E0" tag="0x49070907"/>   <!-- primitive: ∩ -->
  <Function fid="0x902160" tag="0x4C060907"/>   <!-- primitive: ⊣ -->
  <Function fid="0x902120" tag="0x520F0907"/>   <!-- primitive: ⊢ -->
  <Function fid="0x903BC0" tag="0x42010907"/>   <!-- primitive: ! -->
  <Function fid="0x903940" tag="0x4C080907"/>   <!-- primitive: < -->
  <Function fid="0x903A80" tag="0x450A0907"/>   <!-- primitive: = -->
  <Function fid="0x903A40" tag="0x45140907"/>   <!-- primitive: ⊤= -->
  <Function fid="0x9033C0" tag="0x55060907"/>   <!-- primitive: ⊤≠ -->
  <Function fid="0x903C40" tag="0x41040907"/>   <!-- primitive: ∧ -->
  <Function fid="0x903C00" tag="0x410E0907"/>   <!-- primitive: ⊤∧ -->
  <Function fid="0x903740" tag="0x4F020907"/>   <!-- primitive: ∨ -->
  <Function fid="0x903700" tag="0x4F060907"/>   <!-- primitive: ⊤∨ -->
  <Function fid="0x903980" tag="0x4C070907"/>   <!-- primitive: ≤ -->
  <Function fid="0x9038C0" tag="0x4D010907"/>   <!-- primitive: ≥ -->
  <Function fid="0x903400" tag="0x55030907"/>   <!-- primitive: ≠ -->
  <Function fid="0x903A00" tag="0x46020907"/>   <!-- primitive: ⋸ -->
  <Function fid="0x9037C0" tag="0x4E070907"/>   <!-- primitive: ⍱ -->
  <Function fid="0x903780" tag="0x4E0A0907"/>   <!-- primitive: ⊤⍱ -->
  <Function fid="0x903840" tag="0x4E020907"/>   <!-- primitive: ⍲ -->
  <Function fid="0x903800" tag="0x4E090907"/>   <!-- primitive: ⊤⍲ -->
  <Function fid="0x903600" tag="0x50040907"/>   <!-- primitive: ⋆ -->
  <Function fid="0x9036A0" tag="0x50030907"/>   <!-- primitive: + -->
  <Function fid="0x903880" tag="0x4D020907"/>   <!-- primitive: - -->
  <Function fid="0x903540" tag="0x52130907"/>   <!-- primitive: ? -->
  <Function fid="0x903380" tag="0x57020907"/>   <!-- primitive: ∼ -->
  <Function fid="0x9034A0" tag="0x54040907"/>   <!-- primitive: × -->
  <Function fid="0x903AC0" tag="0x44030907"/>   <!-- primitive: ÷ -->
  <Function fid="0x903B60" tag="0x43020907"/>   <!-- primitive: ○ -->
  <Function fid="0x9035C0" tag="0x52120907"/>   <!-- primitive: ⌈ -->
  <Function fid="0x903580" tag="0x52110907"/>   <!-- primitive: ⌊ -->
  <Function fid="0x903500" tag="0x530A0907"/>   <!-- primitive: ∣ -->
  <Function fid="0x903900" tag="0x4C090907"/>   <!-- primitive: ⍟ -->

  <!-- APL values... -->
  <Value flg="0x400" vid="0" parent="-1"1637 rk="1" sh-0="21"/>
  <Value flg="0x400" vid="1" parent="-1"1637 rk="1" sh-0="5"/>
  <Value flg="0x400" vid="2" parent="-1"1637 rk="1" sh-0="256"/>
  <Value flg="0x400" vid="3" parent="-1"1637 rk="0"/>
  <Value flg="0x400" vid="4" parent="-1"1637 rk="0"/>
  <Value flg="0x400" vid="5" parent="-1"1637 rk="1" sh-0="3"/>
  <Value flg="0x400" vid="6" parent="-1"1637 rk="0"/>
  <Value flg="0x400" vid="7" parent="-1"1637 rk="0"/>
  <Value flg="0x400" vid="8" parent="-1"1637 rk="0"/>
  <Value flg="0x400" vid="9" parent="-1"1637 rk="0"/>
  <Value flg="0x400" vid="10" parent="-1"1637 rk="0"/>
  <Value flg="0x400" vid="11" parent="-1"1637 rk="0"/>
  <Value flg="0x400" vid="12" parent="-1"1637 rk="1" sh-0="2"/>
  <Value flg="0x400" vid="13" parent="-1"1637 rk="0"/>
  <Value flg="0x400" vid="14" parent="-1"1637 rk="1" sh-0="0"/>
  <Value flg="0x400" vid="15" parent="-1"1637 rk="0"/>
  <Value flg="0x400" vid="16" parent="-1"1637 rk="0"/>
  <Value flg="0x400" vid="17" parent="-1"1637 rk="0"/>
  <Value flg="0x400" vid="18" parent="-1"1637 rk="0"/>
  <Value flg="0x400" vid="19" parent="-1"1637 rk="0"/>
  <Value flg="0x400" vid="20" parent="-1"1637 rk="0"/>
  <Value flg="0x400" vid="21" parent="-1"1637 rk="0"/>
  <Value flg="0x400" vid="22" parent="-1"1637 rk="1" sh-0="6"/>

  <!-- Ravels of APL values... -->
  <Ravel vid="0" cells="²SystemVariable.cc:740⁰"/>
  <Ravel vid="1" cells="³-1³0³0³0³0"/>
  <Ravel vid="2" cells="¹0¹1¹2¹3¹4¹5¹6¹7¹8¹9¹A
    ¹B¹C¹D¹E¹F¹10¹11¹12¹13¹14¹15¹16¹17¹18¹19¹1A¹1B¹1C¹1D¹1E¹1F² !⁰¹22²#$⁰
    ²%⁰¹26²'()*+,-./0123456789:;⁰¹3C²=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_⁰
    ²`abcdefghijklmnopqrstuvwxyz{|}~¥€⇄∧∼≬⋆⋸⌸⌺⌼μ⍁¡⍣⍅⎕⍞⌹⍆⍤⍇⍈⍊⊤λ⍍⍏£⊥⍶⌶⍐⍑χ⁰
    ²≢⍖⍗⍘⍚⍛⌈⍜⍢∪⍨⍕⍎⍬⍪∣│┤⍟∆∇→╣║╗╝←⌊┐└┴┬├─┼↑↓╔╚╩╦╠═╬≡⍸⍷∵⌷⍂⌻⊢⊣◊┘┌█▄▌▐▀⍺⍹⊂⊃⍝⍲⁰
    ²⍴⍱⌽⊖○∨⍳⍉∈∩⌿⍀≥≤≠×÷⍙∘⍵⍫⍋⍒¯¨ ⁰"/>
  <Ravel vid="3" cells="³0"/>
  <Ravel vid="4" cells="³0"/>
  <Ravel vid="5" cells="¹8¹D¹A
    "/>
  <Ravel vid="6" cells="³0"/>
  <Ravel vid="7" cells="³1"/>
  <Ravel vid="8" cells="³0"/>
  <Ravel vid="9" cells="³0"/>
  <Ravel vid="10" cells="³16807"/>
  <Ravel vid="11" cells="³0"/>
  <Ravel vid="12" cells="³0³0"/>
  <Ravel vid="13" cells="² ⁰"/>
  <Ravel vid="14" cells="² ⁰"/>
  <Ravel vid="15" cells="³0"/>
  <Ravel vid="16" cells="⁴1e-13"/>
  <Ravel vid="17" cells="³1"/>
  <Ravel vid="18" cells="³1"/>
  <Ravel vid="19" cells="³0"/>
  <Ravel vid="20" cells="³10"/>
  <Ravel vid="21" cells="³80"/>
  <Ravel vid="22" cells="².,⋆0_¯⁰"/>

  <!-- Symbol Table -->
  <SymbolTable size="0">
  </SymbolTable>

  <!-- APL system variables... -->
  <Symbol name="⎕AI" stack-size="1">
    <Variable vid="1"/>
  </Symbol>

  <Symbol name="⎕ARG" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="⎕AV" stack-size="1">
    <Variable vid="2"/>
  </Symbol>

  <Symbol name="⎕EM" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="⎕ET" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="⎕LC" stack-size="1">
    <Variable vid="3"/>
  </Symbol>

  <Symbol name="⎕SVE" stack-size="1">
    <Variable vid="4"/>
  </Symbol>

  <Symbol name="⎕TC" stack-size="1">
    <Variable vid="5"/>
  </Symbol>

  <Symbol name="⎕TS" stack-size="1">
    <Variable vid="6"/>
  </Symbol>

  <Symbol name="⎕UL" stack-size="1">
    <Variable vid="7"/>
  </Symbol>

  <Symbol name="⎕WA" stack-size="1">
    <Variable vid="8"/>
  </Symbol>

  <Symbol name="⎕CT" stack-size="1">
    <Variable vid="16"/>
  </Symbol>

  <Symbol name="⎕FC" stack-size="1">
    <Variable vid="22"/>
  </Symbol>

  <Symbol name="⎕IO" stack-size="1">
    <Variable vid="18"/>
  </Symbol>

  <Symbol name="⎕L" stack-size="1">
    <Variable vid="11"/>
  </Symbol>

  <Symbol name="⎕LX" stack-size="1">
    <Variable vid="14"/>
  </Symbol>

  <Symbol name="⎕PP" stack-size="1">
    <Variable vid="20"/>
  </Symbol>

  <Symbol name="⎕PR" stack-size="1">
    <Variable vid="13"/>
  </Symbol>

  <Symbol name="⎕PS" stack-size="1">
    <Variable vid="12"/>
  </Symbol>

  <Symbol name="⎕PW" stack-size="1">
    <Variable vid="21"/>
  </Symbol>

  <Symbol name="⎕R" stack-size="1">
    <Variable vid="9"/>
  </Symbol>

  <Symbol name="⎕RL" stack-size="1">
    <Variable vid="10"/>
  </Symbol>

  <Symbol name="⎕SYL" stack-size="1">
    <Variable vid="15"/>
  </Symbol>

  <Symbol name="⎕TZ" stack-size="1">
    <Variable vid="17"/>
  </Symbol>

  <Symbol name="⎕X" stack-size="1">
    <Variable vid="19"/>
  </Symbol>

  <Symbol name="λ" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="⍺" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="⍵" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="χ" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="⍶" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="⍹" stack-size="1">
    <unused-name/>
  </Symbol>


  <!-- State Indicator -->
  <StateIndicator levels="1">
    <SI-entry level="0" pc="2" line="0">
      <Statements>
        <UCS uni="²+⁰"/>
      </Statements>
      <Parser size="2" assign-pending="0" action="4" lookahead-high="1">
        <Token pc="0" tag="0x50030907" fun-id="0x5003"/>
        <Token pc="1" tag="0x45080205" int="0"/>
        <Token pc="-1" tag="0x56020011"/>
      </Parser>
    </SI-entry>

  </StateIndicator>

</Workspace>
    
